#!/bin/bash

cd "$(dirname "$0")/.."

for i in 'webserver/Cargo.toml' 'frontend/src-wasm/Cargo.toml' 'frontend/src-tauri/Cargo.toml'; do
  echo "context: $(pwd)"
  sed -i "/^version = /cversion = \"$1\"" ${i}
done

sed -i "/^\ \ \"version\": /c\ \ \"version\": \"$1\"," frontend/package.json
