#!/bin/bash

source "$(dirname "$0")/settings"
cd "$(dirname "$0")/.."

for i in $RUST_WORKSPACES; do
  echo "rust workspace: ${i}"
  sed -i "/^version = /cversion = \"$1\"" ${i}/Cargo.toml
done

for i in $YARN_WORKSPACES; do
  echo "yarn workspace: ${i}"
  sed -i "/^\ \ \"version\": /c\ \ \"version\": \"$1\"," ${i}/package.json
done
