#!/bin/bash

cd "$(dirname "$0")/.."
token=$CROWDIN_TOKEN

# make config if not exist
[ -f "crowdin.yml" ] || {
  # make sure it exist
  [ -z "$token" ] && {
    echo "token not set"
    return 1
  }
  sed "s/-TOKEN-/${token}/g" crowdin.example.yml >crowdin.yml
}

# crowdin actions ...
crowdin push || exit 1
crowdin pull || exit 1

# normalize locales
for i in $(ls translations/??_??.json); do
  file_old=$i
  file_new=$(echo "$file_old" | tr '[:upper:]' '[:lower:]')
  [ "$file_old" == "$file_new" ] || {
    cp -f "$file_old" "$file_new" && rm "$file_old"
  }
done

# format default strings
yarn prettier -w src/assets/defaultStrings.json
