#!/bin/bash

cd "$(dirname "$0")/.."
token=$CROWDIN_TOKEN

# make config if not exist
[ -f "crowdin.yml" ] || {
  # make sure it exist
  [ -z "$token" ] && {
    echo "token not set"
    return 1
  }
  sed "s/-TOKEN-/${token}/g" crowdin.example.yml >crowdin.yml
}

# crowdin actions ...
crowdin push
crowdin pull

# normalize locales
for i in $(ls translations/??_??.json); do
  file_old=$i
  file_new=$(echo "$file_old" | tr '[:upper:]' '[:lower:]')
  [ "$file_old" == "$file_new" ] || {
    cp -f "$file_old" "$file_new" && rm "$file_old"
  }
done

# default strings
cp -f translations/de_de.json src/assets/defaultStrings.json
yarn prettier -w src/assets/defaultStrings.json

# git action only update existing ...
#git add -u translations/ src/assets/defaultStrings.json
#git commit -m 'TODO'
#git push
