version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend/"
  schedule:
    interval: daily
    time: "22:30"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/webserver/"
  schedule:
    interval: daily
    time: "22:30"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/crates/"
  schedule:
    interval: daily
    time: "22:30"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/frontend/src-tauri/"
  schedule:
    interval: daily
    time: "22:30"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/frontend/src-wasm/"
  schedule:
    interval: daily
    time: "22:30"
  open-pull-requests-limit: 10
