[package]
name = "config"
version = "0.4.1" # TODO (#1013) set version to 0.0.0
authors = [
  "crapStone <crapstone01@gmail.com>",
  "6543 <6543@obermui.de>",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
directories-next = "2.0.0"
lazy_static = "1.4.0"
log = "0.4.14"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
thiserror = "1.0.29"
tokio = { version = "1.15.0", features = ["fs", "io-util"] }
toml = { version = "0.5.8", features = ["preserve_order"] }
types = { path = "../types/" }

[features]
portable = []
webserver = []
tauri-app = []

default = []
