[package]
name = "cabr2_search"
version = "0.3.0"
authors = [
  "crapStone <crapstone01@gmail.com>",
  "6543 <6543@obermui.de>",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cabr2_types = { path = "../cabr2_types/" }
chrono = "0.4.19"
lazy_static = "1.4.0"
log = "0.4.14"
roxmltree = "0.14.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
structopt = { version = "0.3.21", optional = true }
tauri = { version = "0.11.1", default-features = false, optional = true }
thiserror = "1.0.24"
ureq = { version = "2.1.0", features = ["tls", "json"] }

[features]
handler = []
tauri_plugin = [ "tauri", "handler" ]
default = []

[[bin]]
name = "gestis_helper"
path = "helper/gestis/main.rs"
required-features = [ "structopt" ]
