branches: ["develop", "main"]

pipeline:
  frontend:
    image: codeberg.org/calciumdibromid/cabr2_ci:root
    pull: true
    when:
      path:
        - '.woodpecker/frontend.yml'
        - 'frontend/src/**'
        - 'frontend/*.json'
        - 'frontend/*.js'
        - 'frontend/.prettierignore'
        - 'frontend/yarn.lock'
        - 'frontend/src-wasm/**'

    commands:
      - rustup default stable
      - rustc -V
      - cargo -V
      - node -v
      - yarn --version
      - cd frontend
      - yarn install --frozen-lockfile
      - yarn prettier -c src
      - yarn lint
      - yarn ng build --configuration production
      # debug compiles faster and everything gets checked in the dedicated wasm ci pipeline
      - yarn wasm_lib:debug
      - yarn ng build --configuration webProd
