pipeline:
  tauri-app:
    image: a6543/cabr2_ci:root
    pull: true
    when:
      event:
        - pull_request
      branch:
        - develop
        - main
      path:
        - '.woodpecker/tauri-app.yml'
        - 'frontend/src-tauri/**'

    commands:
      - rustup default stable
      # Fix build
      - mkdir -p frontend/dist/CaBr2 && echo "Hello" > frontend/dist/CaBr2/index.html
      - cd frontend/src-tauri
      - cargo fmt -- --check
      - cargo clippy --all-features -- --deny clippy::all --deny warnings
      - cargo build --all-features
      # does not work, because we need an `yarn install` before
      # - yarn build:release

      # TODO(692) reactivate when tests are written
      #- cargo test --all-features
