branches: ["develop", "main"]

pipeline:
  tauri-app:
    image: codeberg.org/calciumdibromid/cabr2_ci:root
    pull: true
    when:
      path:
        - '.woodpecker/tauri-app.yml'
        - 'frontend/src-tauri/**'
        - 'crates/**'

    commands:
      - rustup default stable
      # Fix build
      - mkdir -p frontend/dist/CaBr2 && echo "Hello" > frontend/dist/CaBr2/index.html
      - cd frontend/src-tauri
      - cargo fmt -- --check
      - cargo clippy --locked --all-features -- --deny clippy::all --deny warnings
      - cargo build --locked --all-features
      # does not work, because we need a `yarn install` before
      # - yarn build:release

      # TODO(692) reactivate when tests are written
      #- cargo test --locked --all-features
