branches: ["develop", "main"]

pipeline:
  wasm-lib:
    image: codeberg.org/calciumdibromid/cabr2_ci:root
    pull: true
    when:
      path:
        - '.woodpecker/wasm-lib.yml'
        - 'frontend/src-wasm/**'

    commands:
      - rustup default stable
      - cd frontend/src-wasm
      - cargo fmt -- --check
      - cargo clippy --locked --all-features -- --deny clippy::all --deny warnings
      - wasm-pack build --out-dir ../cabr2_wasm --dev -- --features debug_build
      - wasm-pack build --out-dir ../cabr2_wasm --release

      # TODO(692) reactivate when tests are written
      #- cargo test --locked --all-features
