[package]
name = "error-ser"
version = "0.0.0"
edition = "2021"
authors = [
  "crapStone <crapstone01@gmail.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.151", features = ["derive"] }
