name: checks

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
    paths:
      - '.github/workflows/backend.yml'
      - 'src-tauri/**'
      - '.gitignore'

jobs:
  backend:
    runs-on: ubuntu-20.04
    container: a6543/cabr2_ci:latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set Rust Toolchain
        run: rustup default stable

      - name: Fix Build
        run: mkdir -p dist/CaBr2 && echo "Hello" > dist/CaBr2/index.html

      - name: Linting
        run: cd src-tauri && cargo clippy -- -D warnings

      - name: Build
        run: cd src-tauri && cargo build

      - name: Tests
        run: ./contrib/for-each-cargo test
