name: checks

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/src/**'
      - 'frontend/*.json'
      - 'frontend/*.js'
      - 'frontend/.prettierignore'
      - 'frontend/yarn.lock'
      - 'frontend/src-wasm/**'

jobs:
  frontend:
    runs-on: ubuntu-20.04
    container: a6543/cabr2_ci:latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set Rust Toolchain
        run: rustup default stable

      - name: Install Dependencies
        run: cd frontend && yarn install --frozen-lockfile

      - name: Check Formatting
        run: cd frontend && yarn prettier -c src

      - name: Eslint
        run: cd frontend && yarn lint

      - name: Build Tauri Frontend
        run: cd frontend && yarn ng build --configuration production

      - name: Build WASM binary
        # debug compiles faster and everything gets checked in the dedicated wasm ci pipeline
        run: cd frontend && yarn wasm_lib:debug

      - name: Build Web Frontend
        run: cd frontend && yarn ng build --configuration webProd
