name: checks

on:
  # Triggers the workflow on push or pull request events but only for the main and develop branches
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  codespell:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
    steps:
      - name: codespell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
          skip: ./.git,./.gitignore,node_modules,dist,yarn.lock,./src/assets,./translations
          ignore_words_list: crate,ser
