name: checks

on:
  # Triggers the workflow on push or pull request events but only for the main and develop branches
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    paths:
      - '.github/workflows/frontend-rust.yml'
      - 'frontend/src-tauri/**'

jobs:
  frontend-rust:
    runs-on: ubuntu-20.04
    container: a6543/cabr2_ci:latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set Rust Toolchain
        run: rustup default stable

      - name: Fix Build
        run: mkdir -p frontend/dist/CaBr2 && echo "Hello" > frontend/dist/CaBr2/index.html

      - name: Lint Tauri app
        run: cd frontend/src-tauri && cargo clippy -- -D warnings

      - name: Build Tauri app
        run: cd frontend/src-tauri && cargo build

      # TODO(692) reactivate when tests are written
      # - name: Test Tauri app
      #   run: cd frontend/src-tauri && cargo test
