name: test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:
    runs-on: ubuntu-20.04
    container: a6543/cabr2_ci:latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: Set Rust Toolchain
        run: rustup default stable

      - name: Rust Linting
        run: ./contrib/for-each-cargo clippy
      - name: Rust Tests
        run: ./contrib/for-each-cargo test

  frontend:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 14
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn ng build
      - run: yarn prettier -w src
