name: test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  backend:
    runs-on: ubuntu-20.04
    container: a6543/cabr2_ci:latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set Rust Toolchain
        run: rustup default stable

      - name: Rust Linting
        run: cd src-tauri && cargo clippy -- -D warnings

      - name: Fix build
        run: mkdir -p dist/CaBr2 && echo "Hello" > dist/CaBr2/index.html

      # should be checked with cargo clippy
      - name: Build Backend
        run: cd src-tauri && cargo build

      - name: Rust Tests
        run: ./contrib/for-each-cargo test

  frontend:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 14
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check Formatting
        run: yarn prettier -c src

      - name: Eslint
        run: yarn lint

      - name: Build Frontend
        run: yarn ng build
