name: test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
      - uses: actions/checkout@v1
      - name: install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev wkhtmltopdf xfonts-base xfonts-75dpi
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb -O /tmp/wkhtmltox_amd64.deb
          sudo dpkg -i /tmp/wkhtmltox_amd64.deb
      - name: Rust Linting
        run: |
          cd ./src-tauri
          cargo clippy
      - name: Rust Tests
        run: |
          cd ./src-tauri
          cargo test

  frontend:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn lint
