name: test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
      - uses: actions/checkout@v1
      - name: Rust Linting
        working-directory: ./src-tauri
        run: cargo clippy
      - name: Rust Tests
        working-directory: ./src-tauri
        run: cargo test
