name: test

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
      - name: Rust Linting
        run: cd src-tauri && cargo clippy
      - name: Rust Tests
        run: cd src-tauri && cargo test
